from .world import World

FULL_GAME_WORLD = World(
    continent_territories={
        "North America": ["Alaska", "Northwest Territory", "Alberta", "Ontario", "Eastern Canada", "Greenland", "Eastern United States", "Western United States", "Central America"],
        "South America": ["Venezuela", "Brazil", "Peru", "Argentina"],
        "Europe": ["Iceland", "Great Britain", "Western Europe", "Southern Europe", "Northern Europe", "Scandinavia", "Russia"],
        "Africa": ["North Africa", "Egypt", "East Africa", "Central Africa", "South Africa", "Madagascar"],
        "Asia": ["Middle East", "Afghanistan", "Ural", "Siberia", "India", "China", "Southeast Asia", "Mongolia", "Japan", "Irkutsk", "Yakutsk", "Kamchatka"],
        "Australia": ["Indonesia", "New Guinea", "Eastern Australia", "Western Australia"]
    },
    continent_troop_gains={
        "North America": 5,
        "South America": 2,
        "Europe": 5,
        "Africa": 3,
        "Asia": 7,
        "Australia": 2
    },
    territory_connections={
        "Alaska": ["Northwest Territory", "Alberta", "Kamchatka"],
        "Northwest Territory": ["Greenland", "Ontario", "Alberta", "Alaska"],
        "Alberta": ["Northwest Territory", "Ontario", "Western United States", "Alaska"],
        "Ontario": ["Northwest Territory", "Greenland", "Eastern Canada", "Eastern United States", "Western United States", "Alberta"],
        "Eastern Canada": ["Greenland", "Eastern United States", "Ontario"],
        "Greenland": ["Iceland", "Eastern Canada", "Ontario", "Northwest Territory"],
        "Eastern United States": ["Ontario", "Eastern Canada", "Central America", "Western United States"],
        "Western United States": ["Alberta", "Ontario", "Eastern United States", "Central America"],
        "Central America": ["Western United States", "Eastern United States", "Venezuela"],
        "Venezuela": ["Central America", "Brazil", "Peru"],
        "Brazil": ["Venezuela", "North Africa", "Argentina", "Peru"],
        "Peru": ["Venezuela", "Brazil", "Argentina"],
        "Argentina": ["Peru", "Brazil"],
        "Iceland": ["Scandinavia", "Great Britain", "Greenland"],
        "Great Britain": ["Iceland", "Scandinavia", "Northern Europe", "Western Europe"],
        "Western Europe": ["Great Britain", "Northern Europe", "Southern Europe", "North Africa"],
        "Southern Europe": ["Northern Europe", "Russia", "Middle East", "Egypt", "North Africa", "Western Europe"],
        "Northern Europe": ["Scandinavia", "Russia", "Southern Europe", "Western Europe", "Great Britain"],
        "Scandinavia": ["Russia", "Northern Europe", "Great Britain", "Iceland"],
        "Russia": ["Ural", "Afghanistan", "Middle East", "Southern Europe", "Northern Europe", "Scandinavia"],
        "North Africa": ["Western Europe", "Southern Europe", "Egypt", "East Africa", "Central Africa", "Brazil"],
        "Egypt": ["Southern Europe", "Middle East", "East Africa", "North Africa"],
        "East Africa": ["Middle East", "Madagascar", "South Africa", "Central Africa", "North Africa", "Egypt"],
        "Central Africa": ["North Africa", "East Africa", "South Africa"],
        "South Africa": ["Central Africa", "East Africa", "Madagascar"],
        "Madagascar": ["East Africa", "South Africa"],
        "Middle East": ["Russia", "Afghanistan", "India", "Egypt", "Southern Europe"],
        "Afghanistan": ["Ural", "China", "India", "Middle East", "Russia"],
        "Ural": ["Siberia", "China", "Afghanistan", "Russia"],
        "Siberia": ["Yakutsk", "Irkutsk", "Mongolia", "China", "Ural"],
        "India": ["China", "Southeast Asia", "Middle East", "Afghanistan"],
        "China": ["Siberia", "Mongolia", "Southeast Asia", "India", "Afghanistan", "Ural"],
        "Southeast Asia": ["China", "Indonesia", "India"],
        "Mongolia": ["Irkutsk", "Kamchatka", "Japan", "China", "Siberia"],
        "Japan": ["Kamchatka", "Mongolia"],
        "Irkutsk": ["Yakutsk", "Kamchatka", "Mongolia", "Siberia"],
        "Yakutsk": ["Kamchatka", "Irkutsk", "Siberia"],
        "Kamchatka": ["Alaska", "Japan", "Mongolia", "Irkutsk", "Yakutsk"],
        "Indonesia": ["Southeast Asia", "New Guinea", "Western Australia"],
        "New Guinea": ["Eastern Australia", "Indonesia"],
        "Eastern Australia": ["New Guinea", "Western Australia"],
        "Western Australia": ["Indonesia", "Eastern Australia"],
    }
)